const itemList = [
  {
    id: 1,
    name: "Pork Ribs",
    price: 10,
    description: "Served with Bbq Sauce",
    course: "starters",
  },
  {
    id: 2,
    name: "Chicken Tenders",
    price: 9,
    description: "Served with Buffalo Sauce",
    course: "starters",
  },
  {
    id: 3,
    name: "Grilled Halloumi",
    price: 8.5,
    description: "Served with Bbq Sauce",
    course: "starters",
  },
  {
    id: 4,
    name: "Brie Cheese",
    price: 8,
    description: "Served with Cranberry Sauce",
    course: "starters",
  },
  {
    id: 5,
    name: "Crispy Cajun Prawns",
    price: 12,
    description: "Served with Cajun Mayo",
    course: "starters",
  },
  {
    id: 6,
    name: "Crispy Calamari",
    price: 10,
    description: "Served with Garlic Mayo & Lemon",
    course: "starters",
  },

  {
    id: 11,
    name: "Margherita",
    price: 14,
    description: "Tomato sauce, mozzarella, basil",
    course: "main",
  },
  {
    id: 12,
    name: "Pepperoni",
    price: 16,
    description: "Tomato sauce, mozzarella, pepperoni",
    course: "main",
  },
  {
    id: 13,
    name: "Hawaiian",
    price: 16,
    description: "Tomato sauce, mozzarella, ham, pineapple",
    course: "main",
  },
  {
    id: 14,
    name: "Four Cheeses",
    price: 18,
    description: "Tomato sauce, mozzarella,smoked cheddar, provolone, parmesan",
    course: "main",
  },
  {
    id: 15,
    name: "Ham & Mushroom",
    price: 15,
    description: "Tomato sauce, mozzarella, ham, mushrooms",
    course: "main",
  },
  {
    id: 16,
    name: "The Veggie",
    price: 17,
    description:
      "Tomato sauce, mozzarella, onions, mushrooms, peppers, olives, tomatoes",
    course: "main",
  },
  {
    id: 21,
    name: "Onion Rings",
    price: 4,
    description: "with ketchup",
    course: "side",
  },
  {
    id: 22,
    name: "Coleslaw",
    price: 4,
    description: "with ketchup",
    course: "side",
  },
  {
    id: 23,
    name: "Fries",
    price: 4,
    description: "with ketchup",
    course: "side",
  },
  {
    id: 24,
    name: "Chips",
    price: 4,
    description: "with ketchup",
    course: "side",
  },
  {
    id: 25,
    name: "Mashed Potatoes",
    price: 4,
    description: "with gravy",
    course: "side",
  },
  {
    id: 26,
    name: "Mixed Veggies",
    price: 4,
    description: "in garlic butter",
    course: "side",
  },
  {
    id: 31,
    name: "Coke",
    price: 4,
    description: "with ice",
    course: "drinks",
  },
  {
    id: 32,
    name: "Pepsi",
    price: 4,
    description: "with ice",
    course: "drinks",
  },
  {
    id: 33,
    name: "Sprite",
    price: 4,
    description: "with ice",
    course: "drinks",
  },
  {
    id: 34,
    name: "Fanta",
    price: 4,
    description: "with ice",
    course: "drinks",
  },
  {
    id: 35,
    name: "Ice Tea",
    price: 4,
    description: "with ice",
    course: "drinks",
  },
  {
    id: 36,
    name: "Water",
    price: 3,
    description: "with ice",
    course: "drinks",
  },

  {
    id: 41,
    name: "Chocolate Cake",
    price: 10,
    description: "with vanilla ice cream",
    course: "desserts",
  },
  {
    id: 42,
    name: "Vanilla Cake",
    price: 10,
    description: "with vanilla ice cream",
    course: "desserts",
  },
  {
    id: 43,
    name: "Strawberry Cake",
    price: 10,
    description: "with strawberry ice cream",
    course: "desserts",
  },
  {
    id: 44,
    name: "Lemon Cake",
    price: 10,
    description: "with lemon ice cream",
    course: "desserts",
  },
  {
    id: 45,
    name: "Cherry Cake",
    price: 10,
    description: "with cherry ice cream",
    course: "desserts",
  },
  {
    id: 46,
    name: "Pineapple Cake",
    price: 10,
    description: "with pineapple ice cream",
    course: "desserts",
  },
];

export default itemList;
